In [28]:
import pandas as pd

In [29]:
from google.colab import files
uploaded = files.upload()

Saving Large_Financials_Dataset.xlsx to Large_Financials_Dataset (1).xlsx

In [41]:
dff = pd.read_excel("Large_Financials_Dataset (1).xlsx")

Working on a copy of a dataset is always better, since it is possible that the original data may get altered.

In [42]:
df = dff.copy()

Finding percentage change of revenue growth, net income growth and assets growth as compared to the previous year.

In [44]:
df['Revenue Growth (%)'] = df.groupby(['Company'])['Total Revenue (USD millions)'].pct_change() * 100

In [45]:
df['Net Income Growth (%)'] = df.groupby(['Company'])['Net Income (USD millions)'].pct_change() * 100

In [46]:
df['Assets Growth (%)'] = df.groupby('Company')['Total Assets (USD millions)'].pct_change() * 100

Dropping the rows containing NaN

In [51]:
df = df.dropna(subset=['Revenue Growth (%)', 'Net Income Growth (%)'])

Summary of revenue growth and net income growth of companies.

In [53]:
company_summary = df.groupby('Company').agg({
    'Revenue Growth (%)': ['mean', 'min', 'max'],
    'Net Income Growth (%)': ['mean', 'min', 'max']
}).reset_index()

In [54]:
company_summary

     Company Revenue Growth (%)                       Net Income Growth (%)  \
                           mean        min        max                  mean
0   Alphabet         -15.910829 -28.793774  -7.817590            -10.595790
1     Amazon         -18.709512 -27.461140  -8.754864           -211.464969
2      Apple          -5.428280 -25.136612   8.333333             -5.717076
3  Microsoft          -9.297188 -15.151515  10.588235            -16.212355
4      Tesla         -31.835922 -45.207586 -12.682073            -37.532091


           min         max
0   -58.957655   54.587302
1 -1322.222222  -13.043478
2   -40.000000   15.217391
3   -58.974359   31.250000
4  -219.556172  101.024590

This shows that on average accross, Apple has the highest Revenue growth, and also the highest net income growth.

Summary of revenue growth and net income growth per year.

In [56]:
year_summary = df.groupby('Fiscal Year').agg({
    'Revenue Growth (%)': 'mean',
    'Net Income Growth (%)': 'mean'
}).reset_index()

In [57]:
year_summary

   Fiscal Year  Revenue Growth (%)  Net Income Growth (%)
0         2015          -12.424548             -14.197732
1         2016          -19.988112             -11.330377
2         2017          -22.885577              -3.065426
3         2018          -11.058121             -12.245187
4         2019          -15.581751             -58.933335
5         2020          -25.635047             -47.698364
6         2021          -14.706718            -274.000000
7         2022           -7.610894             -28.965227

The revenue growth was highest in 2022, whereas the net income growth was highest in 2017.

Finding profit margin

In [58]:
df['Profit Margin (%)'] = (df['Net Income (USD millions)'] / df['Total Revenue (USD millions)']) * 100

/tmp/ipython-input-2889280586.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Profit Margin (%)'] = (df['Net Income (USD millions)'] / df['Total Revenue (USD millions)']) * 100

In [59]:
df

,Company,Fiscal Year,Total Revenue (USD millions),Net Income (USD millions),Total Assets (USD millions),Total Liabilities (USD millions),Cash Flow from Operating Activities (USD millions),Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Profit Margin (%)
1,Microsoft,2022,198000,72000,364000,191000,89000,-6.161137,0.000000,-11.435523,36.363636
2,Microsoft,2021,168000,61000,333000,183000,76000,-15.151515,-15.277778,-8.516484,36.309524
3,Microsoft,2020,143000,44000,301000,183000,60000,-14.880952,-27.868852,-9.609610,30.769231
4,Microsoft,2019,126000,39000,286000,184000,52000,-11.888112,-11.363636,-4.983389,30.952381
5,Microsoft,2018,110000,16000,259000,176000,43000,-12.698413,-58.974359,-9.440559,14.545455
6,Microsoft,2017,96000,21000,241000,162000,39000,-12.727273,31.250000,-6.949807,21.875000
7,Microsoft,2016,85000,16700,193000,121000,33000,-11.458333,-20.476190,-19.917012,19.647059
8,Microsoft,2015,94000,12193,176000,120000,29000,10.588235,-26.988024,-8.808290,12.971277
10,Apple,2022,394000,100000,352000,302000,122000,2.872063,3.092784,0.000000,25.380711
11,Apple,2021,366000,95000,351000,287000,105000,-7.106599,-5.000000,-0.284091,25.956284
12,Apple,2020,274000,57000,323000,258000,81000,-25.136612,-40.000000,-7.977208,20.802920
13,Apple,2019,260000,55000,338000,248000,69000,-5.109489,-3.508772,4.643963,21.153846
14,Apple,2018,266000,59000,365000,258000,77000,2.307692,7.272727,7.988166,22.180451
15,Apple,2017,229000,48000,375000,241000,64000,-13.909774,-18.644068,2.739726,20.960699
16,Apple,2016,216000,46000,321000,193000,66000,-5.676856,-4.166667,-14.400000,21.296296
17,Apple,2015,234000,53000,290000,170000,81000,8.333333,15.217391,-9.657321,22.649573
19,Tesla,2022,81000,12000,82000,36000,14000,-16.494845,-20.000000,-22.641509,14.814815
20,Tesla,2021,54000,5500,62000,31000,11000,-33.333333,-54.166667,-24.390244,10.185185
21,Tesla,2020,31500,721,52000,28500,5100,-41.666667,-86.890909,-16.129032,2.288889
22,Tesla,2019,24578,-862,34400,26200,2400,-21.974603,-219.556172,-33.846154,-3.507202
23,Tesla,2018,21461,-976,29740,23400,2300,-12.682073,13.225058,-13.546512,-4.547784
24,Tesla,2017,11759,-1962,28655,22300,-60,-45.207586,101.024590,-3.648285,-16.685092
25,Tesla,2016,7000,-675,22200,17000,-124,-40.471128,-65.596330,-22.526610,-9.642857
26,Tesla,2015,4000,-889,8000,7000,-524,-42.857143,31.703704,-63.963964,-22.225000
28,Amazon,2022,514000,-2700,462000,389000,46000,-10.452962,-109.000000,-12.333966,-0.525292
29,Amazon,2021,469000,33000,420000,282000,57000,-8.754864,-1322.222222,-9.090909,7.036247
30,Amazon,2020,386000,21000,321000,227000,66000,-17.697228,-36.363636,-23.571429,5.440415
31,Amazon,2019,280000,11500,225000,163000,39000,-27.461140,-45.238095,-29.906542,4.107143
32,Amazon,2018,233000,10000,162000,119000,31000,-16.785714,-13.043478,-28.000000,4.291845
33,Amazon,2017,178000,3000,131000,103000,18000,-23.605150,-70.000000,-19.135802,1.685393
34,Amazon,2016,136000,2370,83300,64000,17000,-23.595506,-21.000000,-36.412214,1.742647
35,Amazon,2015,107000,596,65400,52000,11800,-21.323529,-74.852321,-21.488595,0.557009
37,Alphabet,2022,283000,60000,365000,97000,92000,-7.817590,-18.918919,-9.203980,21.201413
38,Alphabet,2021,257000,76000,359000,97000,92000,-9.187279,26.666667,-1.643836,29.571984
39,Alphabet,2020,183000,40000,320000,93000,65000,-28.793774,-47.368421,-10.863510,21.857923
40,Alphabet,2019,162000,34000,276000,74000,54000,-11.475410,-15.000000,-13.750000,20.987654
41,Alphabet,2018,137000,30700,232000,55000,47000,-15.432099,-9.705882,-15.942029,22.408759
42,Alphabet,2017,111000,12600,198000,44000,37000,-18.978102,-58.957655,-14.655172,11.351351
43,Alphabet,2016,90200,19478,167000,28000,36000,-18.738739,54.587302,-15.656566,21.594235
44,Alphabet,2015,74989,16348,147000,27000,26000,-16.863636,-16.069412,-11.976048,21.800531

In [73]:
df.groupby('Fiscal Year')[['Fiscal Year', 'Profit Margin (%)']]

Ranking by total revenue and net income.

In [60]:
df['Revenue rank'] = df.groupby('Fiscal Year')['Total Revenue (USD millions)'].rank(ascending=False)

/tmp/ipython-input-3608506822.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Revenue rank'] = df.groupby('Fiscal Year')['Total Revenue (USD millions)'].rank(ascending=False)

In [61]:
df['Net Income rank'] = df.groupby('Fiscal Year')['Net Income (USD millions)'].rank(ascending=False)

/tmp/ipython-input-73572582.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df['Net Income rank'] = df.groupby('Fiscal Year')['Net Income (USD millions)'].rank(ascending=False)

In [62]:
df

,Company,Fiscal Year,Total Revenue (USD millions),Net Income (USD millions),Total Assets (USD millions),Total Liabilities (USD millions),Cash Flow from Operating Activities (USD millions),Revenue Growth (%),Net Income Growth (%),Assets Growth (%),Profit Margin (%),Revenue rank,Net Income rank
1,Microsoft,2022,198000,72000,364000,191000,89000,-6.161137,0.000000,-11.435523,36.363636,4.0,2.0
2,Microsoft,2021,168000,61000,333000,183000,76000,-15.151515,-15.277778,-8.516484,36.309524,4.0,3.0
3,Microsoft,2020,143000,44000,301000,183000,60000,-14.880952,-27.868852,-9.609610,30.769231,4.0,2.0
4,Microsoft,2019,126000,39000,286000,184000,52000,-11.888112,-11.363636,-4.983389,30.952381,4.0,2.0
5,Microsoft,2018,110000,16000,259000,176000,43000,-12.698413,-58.974359,-9.440559,14.545455,4.0,3.0
6,Microsoft,2017,96000,21000,241000,162000,39000,-12.727273,31.250000,-6.949807,21.875000,4.0,2.0
7,Microsoft,2016,85000,16700,193000,121000,33000,-11.458333,-20.476190,-19.917012,19.647059,4.0,3.0
8,Microsoft,2015,94000,12193,176000,120000,29000,10.588235,-26.988024,-8.808290,12.971277,3.0,3.0
10,Apple,2022,394000,100000,352000,302000,122000,2.872063,3.092784,0.000000,25.380711,2.0,1.0
11,Apple,2021,366000,95000,351000,287000,105000,-7.106599,-5.000000,-0.284091,25.956284,2.0,1.0
12,Apple,2020,274000,57000,323000,258000,81000,-25.136612,-40.000000,-7.977208,20.802920,2.0,1.0
13,Apple,2019,260000,55000,338000,248000,69000,-5.109489,-3.508772,4.643963,21.153846,2.0,1.0
14,Apple,2018,266000,59000,365000,258000,77000,2.307692,7.272727,7.988166,22.180451,1.0,1.0
15,Apple,2017,229000,48000,375000,241000,64000,-13.909774,-18.644068,2.739726,20.960699,1.0,1.0
16,Apple,2016,216000,46000,321000,193000,66000,-5.676856,-4.166667,-14.400000,21.296296,1.0,1.0
17,Apple,2015,234000,53000,290000,170000,81000,8.333333,15.217391,-9.657321,22.649573,1.0,1.0
19,Tesla,2022,81000,12000,82000,36000,14000,-16.494845,-20.000000,-22.641509,14.814815,5.0,4.0
20,Tesla,2021,54000,5500,62000,31000,11000,-33.333333,-54.166667,-24.390244,10.185185,5.0,5.0
21,Tesla,2020,31500,721,52000,28500,5100,-41.666667,-86.890909,-16.129032,2.288889,5.0,5.0
22,Tesla,2019,24578,-862,34400,26200,2400,-21.974603,-219.556172,-33.846154,-3.507202,5.0,5.0
23,Tesla,2018,21461,-976,29740,23400,2300,-12.682073,13.225058,-13.546512,-4.547784,5.0,5.0
24,Tesla,2017,11759,-1962,28655,22300,-60,-45.207586,101.024590,-3.648285,-16.685092,5.0,5.0
25,Tesla,2016,7000,-675,22200,17000,-124,-40.471128,-65.596330,-22.526610,-9.642857,5.0,5.0
26,Tesla,2015,4000,-889,8000,7000,-524,-42.857143,31.703704,-63.963964,-22.225000,5.0,5.0
28,Amazon,2022,514000,-2700,462000,389000,46000,-10.452962,-109.000000,-12.333966,-0.525292,1.0,5.0
29,Amazon,2021,469000,33000,420000,282000,57000,-8.754864,-1322.222222,-9.090909,7.036247,1.0,4.0
30,Amazon,2020,386000,21000,321000,227000,66000,-17.697228,-36.363636,-23.571429,5.440415,1.0,4.0
31,Amazon,2019,280000,11500,225000,163000,39000,-27.461140,-45.238095,-29.906542,4.107143,1.0,4.0
32,Amazon,2018,233000,10000,162000,119000,31000,-16.785714,-13.043478,-28.000000,4.291845,2.0,4.0
33,Amazon,2017,178000,3000,131000,103000,18000,-23.605150,-70.000000,-19.135802,1.685393,2.0,4.0
34,Amazon,2016,136000,2370,83300,64000,17000,-23.595506,-21.000000,-36.412214,1.742647,2.0,4.0
35,Amazon,2015,107000,596,65400,52000,11800,-21.323529,-74.852321,-21.488595,0.557009,2.0,4.0
37,Alphabet,2022,283000,60000,365000,97000,92000,-7.817590,-18.918919,-9.203980,21.201413,3.0,3.0
38,Alphabet,2021,257000,76000,359000,97000,92000,-9.187279,26.666667,-1.643836,29.571984,3.0,2.0
39,Alphabet,2020,183000,40000,320000,93000,65000,-28.793774,-47.368421,-10.863510,21.857923,3.0,3.0
40,Alphabet,2019,162000,34000,276000,74000,54000,-11.475410,-15.000000,-13.750000,20.987654,3.0,3.0
41,Alphabet,2018,137000,30700,232000,55000,47000,-15.432099,-9.705882,-15.942029,22.408759,3.0,2.0
42,Alphabet,2017,111000,12600,198000,44000,37000,-18.978102,-58.957655,-14.655172,11.351351,3.0,3.0
43,Alphabet,2016,90200,19478,167000,28000,36000,-18.738739,54.587302,-15.656566,21.594235,3.0,2.0
44,Alphabet,2015,74989,16348,147000,27000,26000,-16.863636,-16.069412,-11.976048,21.800531,4.0,2.0

In [68]:
df[['Company', 'Fiscal Year', 'Revenue rank', 'Net Income rank']]

      Company  Fiscal Year  Revenue rank  Net Income rank
1   Microsoft         2022           4.0              2.0
2   Microsoft         2021           4.0              3.0
3   Microsoft         2020           4.0              2.0
4   Microsoft         2019           4.0              2.0
5   Microsoft         2018           4.0              3.0
6   Microsoft         2017           4.0              2.0
7   Microsoft         2016           4.0              3.0
8   Microsoft         2015           3.0              3.0
10      Apple         2022           2.0              1.0
11      Apple         2021           2.0              1.0
12      Apple         2020           2.0              1.0
13      Apple         2019           2.0              1.0
14      Apple         2018           1.0              1.0
15      Apple         2017           1.0              1.0
16      Apple         2016           1.0              1.0
17      Apple         2015           1.0              1.0
19      Tesla         2022           5.0              4.0
20      Tesla         2021           5.0              5.0
21      Tesla         2020           5.0              5.0
22      Tesla         2019           5.0              5.0
23      Tesla         2018           5.0              5.0
24      Tesla         2017           5.0              5.0
25      Tesla         2016           5.0              5.0
26      Tesla         2015           5.0              5.0
28     Amazon         2022           1.0              5.0
29     Amazon         2021           1.0              4.0
30     Amazon         2020           1.0              4.0
31     Amazon         2019           1.0              4.0
32     Amazon         2018           2.0              4.0
33     Amazon         2017           2.0              4.0
34     Amazon         2016           2.0              4.0
35     Amazon         2015           2.0              4.0
37   Alphabet         2022           3.0              3.0
38   Alphabet         2021           3.0              2.0
39   Alphabet         2020           3.0              3.0
40   Alphabet         2019           3.0              3.0
41   Alphabet         2018           3.0              2.0
42   Alphabet         2017           3.0              3.0
43   Alphabet         2016           3.0              2.0
44   Alphabet         2015           4.0              2.0

Finding volatility.

In [63]:
volatility = df.groupby('Company')['Revenue Growth (%)'].std()

In [64]:
volatility

Company
Alphabet      6.707055
Amazon        6.581963
Apple        10.565829
Microsoft     8.497342
Tesla        12.945961
Name: Revenue Growth (%), dtype: float64

Amazon is least volatile with a comparatively steady revenue growth. Tesla is the most volatile.

Finding the companies which had highest Revenue Growth in each year.

In [67]:
df.loc[df.groupby('Fiscal Year')['Revenue Growth (%)'].idxmax(), ['Fiscal Year', 'Company', 'Revenue Growth (%)']].reset_index(drop = True)

   Fiscal Year    Company  Revenue Growth (%)
0         2015  Microsoft           10.588235
1         2016      Apple           -5.676856
2         2017  Microsoft          -12.727273
3         2018      Apple            2.307692
4         2019      Apple           -5.109489
5         2020  Microsoft          -14.880952
6         2021      Apple           -7.106599
7         2022      Apple            2.872063

Conclusion:

Apple has the highest Revenue growth, and also the highest net income growth.
Amazon has the most steadiest revenue growth, whereas Tesla has the least steady revenue growth.
The revenue growth was highest in 2022, whereas the net income growth was highest in 2017.